name: main
on:
  - push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install kind
        uses: helm/kind-action@v1.10.0
        with:
          # renovate: datasource=github-releases depName=kubernetes-sigs/kind
          version: v0.23.0
          install_only: true
      - name: Create the test infrastructure
        run: ./.github/workflows/kind/create.sh
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
      - name: container meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/kubernetes-hello
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
